#!/usr/bin/env bash

base=$(realpath $(dirname $0))
ve="$base/dep/ve2"
vethree="$base/dep/ve3"
py="${ve}/bin/python"
pythree="${vethree}/bin/python"
pipthree="${vethree}/bin/pip"
pip="${ve}/bin/pip"
cd "$base"
git submodule init
git submodule update
if which virtualenv &> /dev/null; then
  virtualenv -p $(which python2) --no-site-packages "$ve"
  virtualenv -p $(which python3) --no-site-packages "$vethree"
elif which conda &> /dev/null; then
  conda create -p "$ve" python=2.7
  conda create -p "$vethree" python=3.5
fi
cd "dep/afew"
"${pythree}" setup.py install
cd "$base"
"${pip}" install -r src/requirements.txt

